MKSHELL=$PLAN9/bin/rc

<$PLAN9/src/mkhdr
TARG=pq\
	pqgen\
	pqsrv\

HFILES=\
	pq.h\
	pqev.h\
	pqsrv.h\

LIB=$PLAN9/lib/libpq.a
BIN=$PLAN9/bin
CLIB=`{ls lib/*.c}
CFLAGS=-I.

<$PLAN9/src/mkmany

$LIB: $CLIB
	@ { cd lib && mk }

clean:V:
	@ { cd lib && mk clean }
	rm -f *.[$OS] *.[$OS].a y.tab.? y.debug y.output

nuke:V:
	@ { cd lib && mk nuke }
	rm -f *.[$OS] *.[$OS].a y.tab.? y.debug y.output [$OS].$TARG $TARG
