<$PLAN9/src/mkhdr

LIB=libpanel.a
OFILES=\
	button.$O\
	canvas.$O\
	draw.$O\
	edit.$O\
	entry.$O\
	event.$O\
	frame.$O\
	group.$O\
#	idollist.$O\
	init.$O\
	label.$O\
	list.$O\
	mem.$O\
	message.$O\
	pack.$O\
	popup.$O\
	print.$O\
	pulldown.$O\
	rtext.$O\
	scroll.$O\
	scrollbar.$O\
	slider.$O\
	textview.$O\
	textwin.$O\
	utf.$O

CFLAGS=-I.
HFILES=panel.h pldefs.h rtext.h

<$PLAN9/src/mklib
